### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by henryruhs** [openknowl/grunt-diff-json#2]
Hello,

I need to compare multiple JSON files - the original JSON includes 2 keys that are not part of the other JSON files.

It would be great to have an array to ignore keys. At the moment I have to create a temporary file for the diff processing and delete it afterwards.

<pre>
var template = safeReadJSON(group.dest); //we need to remove the keys from that one I guess
</pre>

Thank you very much for this great plugin!

**Comment by Lanace** [comment]
unfortunately, we don't have any plan to update the feature

**Comment by henryruhs** [comment]
Sadly, I'd like to show you my workaround. I need to use another Grunt task and create a tempory file:

https://github.com/redaxmedia/redaxscript/blob/3.0.0/gruntfile.js#L212-L251

Please think about adding the feature, I' am willing to support you.

**Comment by Lanace** [comment]
Thanks for the reply.
This project is not maintained anymore.
Because we don't have any time to do it.
Therefore, someone who needs new feature have to create a pull request.
If you make the pull request, we will accept and merge it. thanks :)
